export function GetConfig(): Promise<any>;
export function SaveConfig(arg1: any): Promise<void>;
export function SelectFile(): Promise<string>;
export function SelectDirectory(): Promise<string>;
export function GeneratePar2(arg1: string): Promise<void>;
export function PostToUsenet(arg1: string[], arg2: string, arg3: string): Promise<any>;
export function UploadToAPI(arg1: string, arg2: string, arg3: string): Promise<any>;
export function ProcessFile(arg1: string, arg2: string): Promise<void>;
export function GetFileSize(arg1: string): Promise<number>;
export function ReadFileChunk(arg1: string, arg2: number, arg3: number): Promise<string>;
export function SearchTMDB(arg1: string, arg2: string): Promise<any[]>;
export function GetTMDBDetails(arg1: number, arg2: string): Promise<any>;
export function HistoryList(arg1: any): Promise<any>;
export function HistoryStats(): Promise<any>;
export function HistoryDelete(arg1: number): Promise<void>;
export function HistoryClear(): Promise<void>;
export function SelectFileWithFilter(arg1: string, arg2: string): Promise<string>;
export function ManualUpload(arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<any>;
export function CheckRelease(arg1: string): Promise<{code: number; Explain: string; exists: boolean}>;
export function SaveMediaInfoJSON(arg1: string, arg2: string): Promise<string>;
export function JournalAdd(arg1: string, arg2: string): Promise<void>;
export function JournalList(): Promise<any[]>;
export function JournalClear(): Promise<void>;
export function TestUsenet(): Promise<{success: boolean; message: string}>;
export function GetAppVersion(): Promise<string>;
export function CheckUpdate(): Promise<{available: boolean; latest: string; url: string}>;
