// @ts-check
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
    return window['go']['main']['App']['GetConfig']();
}

export function SaveConfig(arg1) {
    return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectFile() {
    return window['go']['main']['App']['SelectFile']();
}

export function SelectDirectory() {
    return window['go']['main']['App']['SelectDirectory']();
}

export function GeneratePar2(arg1) {
    return window['go']['main']['App']['GeneratePar2'](arg1);
}

export function PostToUsenet(arg1, arg2, arg3) {
    return window['go']['main']['App']['PostToUsenet'](arg1, arg2, arg3);
}

export function UploadToAPI(arg1, arg2, arg3) {
    return window['go']['main']['App']['UploadToAPI'](arg1, arg2, arg3);
}

export function ProcessFile(arg1, arg2) {
    return window['go']['main']['App']['ProcessFile'](arg1, arg2);
}

export function GetFileSize(arg1) {
    return window['go']['main']['App']['GetFileSize'](arg1);
}

export function ReadFileChunk(arg1, arg2, arg3) {
    return window['go']['main']['App']['ReadFileChunk'](arg1, arg2, arg3);
}

export function SearchTMDB(arg1, arg2) {
    return window['go']['main']['App']['SearchTMDB'](arg1, arg2);
}

export function GetTMDBDetails(arg1, arg2) {
    return window['go']['main']['App']['GetTMDBDetails'](arg1, arg2);
}

export function HistoryList(arg1) {
    return window['go']['main']['App']['HistoryList'](arg1);
}

export function HistoryStats() {
    return window['go']['main']['App']['HistoryStats']();
}

export function HistoryDelete(arg1) {
    return window['go']['main']['App']['HistoryDelete'](arg1);
}

export function HistoryClear() {
    return window['go']['main']['App']['HistoryClear']();
}

export function SelectFileWithFilter(arg1, arg2) {
    return window['go']['main']['App']['SelectFileWithFilter'](arg1, arg2);
}

export function ManualUpload(arg1, arg2, arg3, arg4, arg5) {
    return window['go']['main']['App']['ManualUpload'](arg1, arg2, arg3, arg4, arg5);
}

export function CheckRelease(arg1) {
    return window['go']['main']['App']['CheckRelease'](arg1);
}

export function SaveMediaInfoJSON(arg1, arg2) {
    return window['go']['main']['App']['SaveMediaInfoJSON'](arg1, arg2);
}

export function JournalAdd(arg1, arg2) {
    return window['go']['main']['App']['JournalAdd'](arg1, arg2);
}

export function JournalList(arg1) {
    return window['go']['main']['App']['JournalList'](arg1);
}

export function JournalClear() {
    return window['go']['main']['App']['JournalClear']();
}

export function TestUsenet() {
    return window['go']['main']['App']['TestUsenet']();
}

export function GetAppVersion() {
    return window['go']['main']['App']['GetAppVersion']();
}

export function CheckUpdate() {
    return window['go']['main']['App']['CheckUpdate']();
}
